const allowed={date:["date","booking date","start date","booking day"],court:["court(s)","court","court name","court number","resource","facility"],category:["booking category","category","activity"],duration:["duration","duration minutes","minutes","length"],time:["time of booking","start time","from","time from","booking start"],bookingType:["booking type","recurrence","repeat type"],membershipStatus:["membership status","member status","membership"]};
const fileInput=document.getElementById("workbookFile"),status=document.getElementById("publisherStatus"),summary=document.getElementById("publisherSummary"),download=document.getElementById("downloadJson");let payload=null;
const clean=value=>String(value??"").trim().toLocaleLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");
function findColumn(headers,aliases){return headers.findIndex(header=>aliases.includes(clean(header)))}
function isoDate(value){if(value instanceof Date&&!Number.isNaN(value))return value.toISOString().slice(0,10);if(typeof value==="number"){const date=XLSX.SSF.parse_date_code(value);return date?`${date.y}-${String(date.m).padStart(2,"0")}-${String(date.d).padStart(2,"0")}`:""}const date=new Date(value);if(!Number.isNaN(date))return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;return ""}
function timeText(value){if(value instanceof Date&&!Number.isNaN(value))return `${String(value.getHours()).padStart(2,"0")}:${String(value.getMinutes()).padStart(2,"0")}`;if(typeof value==="number"){const minutes=Math.round((value%1)*1440);return `${String(Math.floor(minutes/60)%24).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`}const match=String(value??"").match(/(\d{1,2}):(\d{2})/);return match?`${String(Number(match[1])).padStart(2,"0")}:${match[2]}`:""}
function durationMinutes(value){if(typeof value==="number")return value>0&&value<1?Math.round(value*1440):Math.round(value);const parsed=Number(String(value??"").replace(/[^\d.]/g,""));return Number.isFinite(parsed)?Math.round(parsed):0}
fileInput.addEventListener("change",async()=>{const file=fileInput.files[0];if(!file)return;try{status.textContent=`Reading ${file.name}…`;download.disabled=true;const workbook=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];const table=XLSX.utils.sheet_to_json(sheet,{header:1,defval:"",raw:true});if(!table.length)throw new Error("The first worksheet is empty");const headers=table[0];const indexes=Object.fromEntries(Object.entries(allowed).map(([key,aliases])=>[key,findColumn(headers,aliases)]));const missing=Object.entries(indexes).filter(([,index])=>index<0).map(([key])=>key);if(missing.length)throw new Error(`Required columns not found: ${missing.join(", ")}`);const rows=table.slice(1).map(row=>({date:isoDate(row[indexes.date]),court:String(row[indexes.court]??"").trim(),category:String(row[indexes.category]??"").trim(),duration:durationMinutes(row[indexes.duration]),time:timeText(row[indexes.time]),bookingType:String(row[indexes.bookingType]??"").trim(),membershipStatus:String(row[indexes.membershipStatus]??"").trim()})).filter(row=>Object.values(row).some(Boolean));payload={generatedAt:new Date().toISOString(),sourceFile:file.name,rows};summary.hidden=false;summary.textContent=`Ready: ${rows.length.toLocaleString()} records. Only the seven approved booking fields will be exported.`;status.textContent="Workbook validated successfully.";download.disabled=false}catch(error){payload=null;summary.hidden=true;status.textContent=error.message}});
download.addEventListener("click",()=>{if(!payload)return;const blob=new Blob([`${JSON.stringify(payload,null,2)}\n`],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="bookings.json";link.click();URL.revokeObjectURL(link.href)});
